-- BooKI initial schema (PostgreSQL).
--
-- A single baseline. Flyway has only run against throwaway dev/pilot databases,
-- so there is no incremental history worth preserving — the schema is rewritten
-- in place rather than layered with V2/V3. Before deploying a change to this
-- file, wipe the target database (drop all tables incl. flyway_schema_history)
-- so this migration re-runs clean. See ADR-011, ADR-015 and ADR-017.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name          VARCHAR(255) NOT NULL DEFAULT '',
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- The user's chosen default reader profile. NULL = fall back to the built-in
    -- "General reader". The FK is added below, once reader_profiles exists.
    default_reader_profile_id BIGINT
);

CREATE TABLE documents (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users (id),
    title      VARCHAR(500) NOT NULL,
    file_path  VARCHAR(1000) NOT NULL,
    page_count INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE document_pages (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id    BIGINT NOT NULL REFERENCES documents (id),
    page_number    INTEGER NOT NULL,
    extracted_text TEXT NOT NULL,
    UNIQUE (document_id, page_number)
);

-- An AI Profile = the "master" a session runs on: persona, difficulty rubrics,
-- per-function prompts, capability routing. Every account is seeded with an
-- editable copy of each shipped template at registration (templates live in
-- the versioned prompt catalog loaded by SlotPromptCatalog, not the DB).
CREATE TABLE ai_profiles (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL REFERENCES users (id),
    name                 VARCHAR(255) NOT NULL,
    based_on_template    VARCHAR(40) NOT NULL,
    is_default           BOOLEAN NOT NULL DEFAULT FALSE,
    enabled_capabilities VARCHAR(120) NOT NULL DEFAULT 'explain,mnemonic,quiz,summary',
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ai_profile_slot_prompts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id    BIGINT NOT NULL REFERENCES ai_profiles (id) ON DELETE CASCADE,
    slot          VARCHAR(40) NOT NULL,
    text          TEXT NOT NULL,
    original_text TEXT NOT NULL,
    UNIQUE (profile_id, slot)
);

-- A Reader Profile = who is reading, in one study context. No link to any AI
-- Profile — a session picks one. user_id NULL marks a shipped, read-only reader
-- template (seeded below); everyone sees those plus their own.
CREATE TABLE reader_profiles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT REFERENCES users (id) ON DELETE CASCADE,
    name         VARCHAR(255) NOT NULL,
    context      TEXT NOT NULL DEFAULT '',
    reader_level VARCHAR(20),
    is_default   BOOLEAN NOT NULL DEFAULT FALSE,
    read_only    BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO reader_profiles (user_id, name, context, is_default, read_only) VALUES (
    NULL,
    'General reader',
    'What I want to get out of this reading: ' || CHR(10)
        || 'How familiar I already am with the topic: ' || CHR(10)
        || 'How I learn best (worked examples, plain definitions, analogies, a slower pace...): ' || CHR(10)
        || 'Anything that helps me follow along (short paragraphs, no jargon, dyslexia-friendly formatting...): ',
    TRUE,
    TRUE
), (
    NULL,
    'Dyslexia-friendly reader',
    'This reader benefits from dyslexia-friendly support.' || CHR(10)
        || 'Prioritize meaning and comprehension over reading speed, spelling, handwriting, or exact wording.' || CHR(10)
        || 'Use short sentences, small paragraphs, and one instruction or question at a time.' || CHR(10)
        || 'Keep the intellectual content intact; do not infantilize or infer ability from decoding difficulty.' || CHR(10)
        || 'Accept brief, approximate, or spoken answers. Respond to the idea first and offer only one correction or next step at a time.' || CHR(10)
        || 'Explain or split a difficult word when it is important or requested, and rephrase patiently when something does not land.',
    FALSE,
    TRUE
);

-- Per-user default reader profile (see users table). ON DELETE SET NULL so
-- deleting the profile a user had defaulted to just drops them back to the
-- built-in "General reader".
ALTER TABLE users
    ADD CONSTRAINT fk_users_default_reader_profile
    FOREIGN KEY (default_reader_profile_id) REFERENCES reader_profiles (id) ON DELETE SET NULL;

CREATE TABLE sessions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL REFERENCES users (id),
    document_id       BIGINT NOT NULL REFERENCES documents (id),
    start_page        INTEGER NOT NULL,
    end_page          INTEGER NOT NULL,
    current_page      INTEGER NOT NULL,
    ai_profile_id     BIGINT REFERENCES ai_profiles (id) ON DELETE SET NULL,
    reader_profile_id BIGINT REFERENCES reader_profiles (id) ON DELETE SET NULL,
    difficulty        VARCHAR(20) NOT NULL,
    language          VARCHAR(10) NOT NULL DEFAULT 'en',
    ai_provider       VARCHAR(20),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE messages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES sessions (id),
    speaker    VARCHAR(20) NOT NULL,
    input_type VARCHAR(20) NOT NULL,
    message    TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tags (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users (id),
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tag_documents (
    tag_id      BIGINT NOT NULL REFERENCES tags (id),
    document_id BIGINT NOT NULL REFERENCES documents (id),
    PRIMARY KEY (tag_id, document_id)
);

CREATE TABLE quiz_attempts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    BIGINT NOT NULL REFERENCES sessions (id),
    page_number   INTEGER NOT NULL,
    question      TEXT NOT NULL,
    answer        TEXT NOT NULL,
    difficulty    VARCHAR(20) NOT NULL,
    ai_profile_id BIGINT REFERENCES ai_profiles (id) ON DELETE SET NULL,
    correct       BOOLEAN NOT NULL,
    score         DOUBLE PRECISION NOT NULL,
    feedback      TEXT NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sent_reports (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES sessions (id),
    type       VARCHAR(20) NOT NULL,
    email      VARCHAR(255),
    file_name  VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
