-- BooKI initial schema (PostgreSQL).
--
-- This single baseline replaces the former MySQL migrations V1..V9. Flyway had
-- never run against a deployed database, so there was no incremental history
-- worth preserving: rewriting one clean Postgres file is safer than porting
-- nine. It is the net result of the old V1..V9 applied in order:
--   V2  user profile fields (name, bio, system_prompt)
--   V3  sessions.language
--   V4  tags + tag_documents
--   V5  quiz_attempts
--   V6  sent_reports
--   V7  Profile Master seed translated to English (folded into the seed below)
--   V8  profile_masters.user_id (per-user copies; NULL rows are seed templates)
--   V9  sessions.ai_provider
-- The next schema change is a normal incremental V2.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name          VARCHAR(255) NOT NULL DEFAULT '',
    bio           TEXT,
    system_prompt TEXT,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE documents (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users (id),
    title      VARCHAR(500) NOT NULL,
    file_path  VARCHAR(1000) NOT NULL,
    page_count INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE document_pages (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id    BIGINT NOT NULL REFERENCES documents (id),
    page_number    INTEGER NOT NULL,
    extracted_text TEXT NOT NULL,
    UNIQUE (document_id, page_number)
);

CREATE TABLE profile_masters (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT REFERENCES users (id),   -- NULL => seed template
    name          VARCHAR(255) NOT NULL,
    description   TEXT NOT NULL,
    system_prompt TEXT NOT NULL,
    config_json   TEXT NOT NULL,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE sessions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL REFERENCES users (id),
    document_id       BIGINT NOT NULL REFERENCES documents (id),
    start_page        INTEGER NOT NULL,
    end_page          INTEGER NOT NULL,
    current_page      INTEGER NOT NULL,
    profile_master_id BIGINT REFERENCES profile_masters (id),
    difficulty        VARCHAR(20) NOT NULL,
    language          VARCHAR(10) NOT NULL DEFAULT 'en',
    ai_provider       VARCHAR(20),
    config_json       TEXT NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at      TIMESTAMP WITH TIME ZONE
);

CREATE TABLE messages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES sessions (id),
    speaker    VARCHAR(20) NOT NULL,
    input_type VARCHAR(20) NOT NULL,
    message    TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tags (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users (id),
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tag_documents (
    tag_id      BIGINT NOT NULL REFERENCES tags (id),
    document_id BIGINT NOT NULL REFERENCES documents (id),
    PRIMARY KEY (tag_id, document_id)
);

CREATE TABLE quiz_attempts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id        BIGINT NOT NULL REFERENCES sessions (id),
    page_number       INTEGER NOT NULL,
    question          TEXT NOT NULL,
    answer            TEXT NOT NULL,
    difficulty        VARCHAR(20) NOT NULL,
    profile_master_id BIGINT REFERENCES profile_masters (id),
    correct           BOOLEAN NOT NULL,
    score             DOUBLE PRECISION NOT NULL,
    feedback          TEXT NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sent_reports (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES sessions (id),
    type       VARCHAR(20) NOT NULL,
    email      VARCHAR(255),
    file_name  VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seed: the 4 default Profile Master templates (user_id NULL). At registration
-- each new user gets their own editable copy of these. English text per the
-- former V7.
INSERT INTO profile_masters (user_id, name, description, system_prompt, config_json, is_active) VALUES
(NULL, 'Grade 3 teacher from Quebec', 'Explains with patience, simple vocabulary, and everyday examples.', 'You are a third-grade teacher in Quebec. You explain calmly, use simple words, give everyday examples, and encourage the reader without pressuring them.', '{}', TRUE),
(NULL, 'Science teacher', 'Explains scientific concepts rigorously but accessibly.', 'You are a passionate science teacher. You explain concepts rigorously, use analogies, and connect ideas to the real world.', '{}', TRUE),
(NULL, 'Literary critic', 'Analyzes characters, symbolism, and narrative style.', 'You are a kind literary critic. You help analyze characters, symbolism, narrative choices, and the author''s style.', '{}', TRUE),
(NULL, 'Learning difficulties specialist', 'Adapts explanations to a slower pace and offers clear hints.', 'You are a learning difficulties specialist. You break information into smaller pieces, repeat key concepts in different words, and give very clear hints.', '{}', TRUE);
